"""Sprite registry. Two sources:
1. Procedural pixel art authored as character maps (always available).
2. The GothicVania Cemetery pack (CC0, Ansimuz) under assets/pack/ — loaded at
   half scale so its pixel density matches the internal view. When present it
   overrides the registry and sets PACK=True (better animations, held weapon).
Deleting assets/pack/ cleanly falls back to the procedural art."""
import os

import pygame

from . import paths

PACK = False
PACK_DIR = os.path.join(paths.resource_dir(), "assets", "pack")

PAL = {
    "K": (12, 10, 16),     # outline / dark
    "W": (224, 220, 202),  # bone
    "w": (170, 164, 150),  # bone shade
    "R": (220, 60, 50),    # eye red
    "H": (222, 178, 140),  # skin
    "h": (74, 52, 38),     # hair
    "A": (92, 102, 128),   # armor
    "a": (58, 64, 86),     # armor dark
    "C": (122, 38, 46),    # cape
    "B": (205, 214, 228),  # blade
    "b": (142, 152, 172),  # blade shade
    "G": (192, 152, 62),   # gold
    "L": (98, 68, 42),     # leather
    "D": (70, 52, 34),     # wood
    "S": (112, 108, 122),  # stone
    "s": (80, 76, 90),     # stone shade
    "M": (62, 92, 56),     # moss
    "O": (217, 119, 87),   # claude orange
    "o": (162, 82, 58),    # claude orange dark
    "P": (98, 62, 132),    # purple robe
    "p": (62, 38, 86),     # purple robe dark
    "Y": (242, 222, 132),  # glow yellow
    "T": (84, 222, 200),   # teal magic
}

PLAYER_IDLE1 = """\
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HKHHKH.......
...HHHHHH.......
....HHHH........
..AAAAAAA.......
.CAAAAAAAA......
.CAaAAAAaAH.....
.CAAAAAAAA......
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
...AAAAAA.......
...Aa..aA.......
...Aa..aA.......
...Aa..aA.......
...LL..LL.......
..LLL..LLL......
................
"""

PLAYER_IDLE2 = """\
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HHHHHH.......
...HHHHHH.......
....HHHH........
..AAAAAAA.......
.CAAAAAAAA......
.CAaAAAAaAH.....
.CAAAAAAAA......
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
...AAAAAA.......
...Aa..aA.......
...Aa..aA.......
...Aa..aA.......
...LL..LL.......
..LLL..LLL......
................
"""

PLAYER_RUN1 = """\
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HKHHKH.......
...HHHHHH.......
....HHHH........
..AAAAAAA.......
.CAAAAAAAA......
.CAaAAAAaAH.....
.CAAAAAAAA......
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
...AAAAAA.......
...Aa...aA......
..Aa.....aA.....
..La......La....
..LL......LL....
.LLL.......LL...
................
"""

PLAYER_RUN2 = """\
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HKHHKH.......
...HHHHHH.......
....HHHH........
..AAAAAAA.......
.CAAAAAAAA......
.CAaAAAAaAH.....
.CAAAAAAAA......
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
...AAAAAA.......
....AaAa........
....AaAa........
....LaLa........
....LLLL........
...LLL.LL.......
................
"""

PLAYER_JUMP = """\
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HKHHKH.......
...HHHHHH.......
....HHHH........
..AAAAAAA.......
.CAAAAAAAAH.....
.CAaAAAAaA......
.CAAAAAAAA......
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
...AAAAAA.......
...AaaaaA.......
...LL..LL.......
..LL....LL......
................
................
................
"""

PLAYER_CROUCH = """\
................
................
................
................
....hhhh........
...hhhhhh.......
...HHHHHH.......
...HKHHKH.......
...HHHHHH.......
..AAAAAAA.......
.CAAAAAAAAH.....
.CAaAAAAaA......
..AAAAAAAA......
..LLLLLLLL......
..Aa....aA......
..LL....LL......
.LLL....LLL.....
................
................
................
"""

SWORD = """\
.G..........
GGBBBBBBBBBb
.G..........
"""

SKEL_WALK1 = """\
....WWWW....
...WWWWWW...
...WRWWRW...
...WWWWWW...
....WwWw....
.....WW.....
...WWWWWW...
..w.WwWw.w..
..w.WWWW.w..
..W.WwWw.W..
....WWWW....
....w..w....
....W..W....
....w..w....
...WW..WW...
............
"""

SKEL_WALK2 = """\
....WWWW....
...WWWWWW...
...WRWWRW...
...WWWWWW...
....WwWw....
.....WW.....
...WWWWWW...
..w.WwWw.w..
..w.WWWW.w..
..W.WwWw.W..
....WWWW....
...w....w...
...W....W...
....w..w....
..WW....WW..
............
"""

SKEL_ATTACK = """\
....WWWW....
...WWWWWW...
...WRWWRW...
...WWWWWW...
....WwWw....
.....WW.....
...WWWWWW...
..w.WwWwWWw.
..w.WWWW....
..W.WwWw....
....WWWW....
....w..w....
....W..W....
....w..w....
...WW..WW...
............
"""

SKEL_RISE = """\
....WWWW....
...WWWWWW...
...WRWWRW...
...WWWWWW...
....WwWw....
.....WW.....
...WWWWWW...
..wWWwWwWw..
............
............
............
............
............
............
............
............
"""

GRAVE1 = """\
..SSSSS..
.SSSSSSS.
.SsSSSsS.
.SSSSSSS.
.SsSSSsS.
.SSSSSSS.
.SSSSSSS.
.MSSSSSM.
.SSSSSSS.
MSSSSSSSM
"""

GRAVE2 = """\
....S....
...SSS...
....S....
..SSSSS..
.SSSSSSS.
..SSSSS..
....S....
....S....
....S....
...SSS...
..SSSSS..
.MSSSSSM.
"""

GRAVE3 = """\
.SSSSSS..
.SssssS..
.SSSSSS..
.SssssS..
.SSSSSS..
MSSSSSSM.
"""

DEAD_BUSH = """\
.D..D..D.
..D.D.D..
...DDD...
..D.DD...
....D....
....D....
...DD....
"""

FENCE = """\
D..D..D..D..
DDDDDDDDDDDD
D..D..D..D..
D..D..D..D..
DDDDDDDDDDDD
D..D..D..D..
"""

LANTERN = """\
..D..
.DDD.
.DYD.
.DYD.
.DDD.
..D..
..D..
..D..
"""

SKULL_PILE = """\
..WW....
.WWWW.W.
WWKWWWWW
WWWWKWWW
wWWwWWww
"""

ARROW = """\
.DDDDB.
WDDDDBB
.DDDDB.
"""


def _surf(map_str):
    rows = [r for r in map_str.splitlines() if r]
    w = max(len(r) for r in rows)
    s = pygame.Surface((w, len(rows)), pygame.SRCALPHA)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != ".":
                s.set_at((x, y), PAL[ch])
    return s


def _recolor(map_str, table, from_row=0):
    rows = map_str.splitlines()
    out = []
    for i, row in enumerate(rows):
        if i >= from_row:
            row = "".join(table.get(ch, ch) for ch in row)
        out.append(row)
    return "\n".join(out)


_S = {}


def build():
    _S["player_idle"] = [_surf(PLAYER_IDLE1), _surf(PLAYER_IDLE2)]
    _S["player_run"] = [_surf(PLAYER_RUN1), _surf(PLAYER_RUN2)]
    _S["player_jump"] = [_surf(PLAYER_JUMP)]
    _S["player_crouch"] = [_surf(PLAYER_CROUCH)]
    _S["sword"] = [_surf(SWORD)]

    _S["skel_bare"] = [_surf(SKEL_WALK1), _surf(SKEL_WALK2), _surf(SKEL_ATTACK)]
    _S["skel_sword"] = [_surf(_recolor(m, {"w": "K"}))
                        for m in (SKEL_WALK1, SKEL_WALK2, SKEL_ATTACK)]
    # archer keeps a bone body under a leather hood (recolor the skull rows only)
    _S["skel_archer"] = [_surf(_hood(m))
                         for m in (SKEL_WALK1, SKEL_WALK2, SKEL_ATTACK)]
    _S["skel_mage"] = [_surf(_recolor(m, {"W": "P", "w": "p", "R": "Y"}, from_row=5))
                       for m in (SKEL_WALK1, SKEL_WALK2, SKEL_ATTACK)]
    _S["skel_claude"] = [_surf(_recolor(m, {"W": "O", "w": "o", "R": "Y"}))
                         for m in (SKEL_WALK1, SKEL_WALK2, SKEL_ATTACK)]
    _S["skel_rise"] = [_surf(SKEL_RISE)]

    _S["grave1"] = [_surf(GRAVE1)]
    _S["grave2"] = [_surf(GRAVE2)]
    _S["grave3"] = [_surf(GRAVE3)]
    _S["dead_bush"] = [_surf(DEAD_BUSH)]
    _S["fence"] = [_surf(FENCE)]
    _S["lantern"] = [_surf(LANTERN)]
    _S["skull_pile"] = [_surf(SKULL_PILE)]
    _S["arrow"] = [_surf(ARROW)]


def _hood(map_str):
    """Archer: leather hood on the skull, bone body."""
    return "\n".join(
        "".join({"W": "L", "w": "L"}.get(ch, ch) for ch in row) if i < 2 else row
        for i, row in enumerate(map_str.splitlines()))


def _load_half(name):
    s = pygame.image.load(os.path.join(PACK_DIR, name)).convert_alpha()
    return pygame.transform.scale_by(s, 0.5)


def _tint(surf, color):
    s = surf.copy()
    s.fill(color, special_flags=pygame.BLEND_RGB_MULT)
    return s


def _flip_all(frames):
    """Pack enemies natively face LEFT; the game treats right as neutral."""
    return [pygame.transform.flip(f, True, False) for f in frames]


def _brighten(surf, amt=(30, 30, 42)):
    s = surf.copy()
    s.fill(amt, special_flags=pygame.BLEND_RGB_ADD)
    return s


def _outline(surf, color=(8, 6, 14)):
    """1px dark rim so enemies read against the murky background."""
    mask = pygame.mask.from_surface(surf)
    sil = mask.to_surface(setcolor=(*color, 255), unsetcolor=(0, 0, 0, 0))
    out = pygame.Surface((surf.get_width() + 2, surf.get_height() + 2),
                         pygame.SRCALPHA)
    for dx, dy in ((0, 1), (2, 1), (1, 0), (1, 2)):
        out.blit(sil, (dx, dy))
    out.blit(surf, (1, 1))
    return out


def _enemy_frames(names, ghost=False):
    frames = _flip_all(_load_half(n) for n in names)
    if ghost:
        frames = [_brighten(f) for f in frames]
    return [_outline(f) for f in frames]


def load_pack():
    """Override procedural entries with GothicVania Cemetery art if present."""
    global PACK
    if not os.path.isdir(PACK_DIR):
        return
    try:
        _S["player_idle"] = [_load_half(f"hero-idle-{i}.png") for i in range(1, 5)]
        _S["player_run"] = [_load_half(f"hero-run-{i}.png") for i in range(1, 7)]
        _S["player_attack"] = [_load_half(f"hero-attack-{i}.png") for i in range(1, 6)]
        _S["player_jump"] = [_load_half(f"hero-jump-{i}.png") for i in range(1, 5)]
        _S["player_crouch"] = [_load_half("hero-crouch.png")]
        _S["player_hurt"] = [_load_half("hero-hurt.png")]
        _S["skel_bare"] = _enemy_frames([f"skeleton-{i}.png" for i in range(1, 9)])
        _S["skel_sword"] = _enemy_frames([f"skeleton-clothed-{i}.png"
                                          for i in range(1, 9)])
        _S["skel_bare_rise"] = _enemy_frames([f"skeleton-rise-{i}.png"
                                              for i in range(1, 7)])
        _S["skel_sword_rise"] = _enemy_frames([f"skeleton-rise-clothed-{i}.png"
                                               for i in range(1, 7)])
        _S["enemy_death"] = _enemy_frames([f"enemy-death-{i}.png"
                                           for i in range(1, 6)])
        _S["skel_archer"] = _enemy_frames([f"ghost-{i}.png" for i in range(1, 5)],
                                          ghost=True)
        _S["skel_mage"] = _enemy_frames([f"ghost-halo-{i}.png"
                                         for i in range(1, 5)], ghost=True)
        # claude messenger: the hooded (clothed) skeleton as a spectral cyan ghost
        _S["skel_claude"] = [_tint(f, (150, 235, 255)) for f in _S["skel_sword"]]
        _S["grave1"] = [_load_half("stone-1.png")]
        _S["grave2"] = [_load_half("stone-2.png")]
        _S["grave3"] = [_load_half("stone-3.png")]
        _S["grave4"] = [_load_half("stone-4.png")]
        _S["statue"] = [_load_half("statue.png")]
        _S["bush_large"] = [_load_half("bush-large.png")]
        _S["bush_small"] = [_load_half("bush-small.png")]
        _S["bg_tree1"] = [_load_half("tree-1.png")]
        _S["bg_tree2"] = [_load_half("tree-2.png")]
        _S["bg_tree3"] = [_load_half("tree-3.png")]
        PACK = True
    except (pygame.error, FileNotFoundError, OSError):
        PACK = False


def has(name):
    return name in _S


def load_layer_half(filename):
    """Half-scale environment layer from the pack, or None."""
    try:
        return _load_half(filename)
    except (pygame.error, FileNotFoundError, OSError):
        return None


def get(name):
    return _S[name]


_flip_cache = {}


def flipped(surf):
    key = id(surf)
    if key not in _flip_cache:
        _flip_cache[key] = pygame.transform.flip(surf, True, False)
    return _flip_cache[key]


_white_cache = {}


def white(surf):
    """Solid-white silhouette for hit flashes."""
    key = id(surf)
    if key not in _white_cache:
        s = surf.copy()
        s.fill((255, 255, 255), special_flags=pygame.BLEND_RGB_MAX)
        _white_cache[key] = s
    return _white_cache[key]
